import {
  Anchor,
  Building2,
  Car,
  CircleHelp,
  Compass,
  Hotel,
  House,
  Landmark,
  Mail,
  MapPinned,
  Newspaper,
  Palmtree,
  Plane,
  Route,
  Ship,
  Star,
  Tags,
  type LucideIcon,
} from "lucide-react";
import type { NavItem } from "@/lib/site-config";

export const navIcons: Record<NavItem["href"], LucideIcon> = {
  "/": House,
  "/airport-transfer": Plane,
  "/hotel-transfer": Hotel,
  "/pier-transfer": Ship,
  "/beach-transfer": Palmtree,
  "/city-transfer": Building2,
  "/attraction-transfer": Landmark,
  "/inter-province-transfer": Route,
  "/fleet": Car,
  "/price-list": Tags,
  "/tours": Compass,
  "/boat-schedules": Anchor,
  "/travel-info": MapPinned,
  "/articles": Newspaper,
  "/faq": CircleHelp,
  "/reviews": Star,
  "/contact": Mail,
};
