export const siteConfig = {
  name: "KRABI LINKS TAXI",
  shortName: "Krabi Links",
  domain: "www.krabilinkstaxi.com",
  slogan: "เชื่อมทุกเส้นทางของภาคใต้",
  sloganEn: "Your Trusted Southern Thailand Transfer Network",
  tagline: "Southern Thailand Travel & Transportation Platform",
  phone: "+66 75 123 456",
  email: "booking@krabilinkstaxi.com",
  line: "@krabilinkstaxi",
  address: "Krabi Town, Krabi 81000, Thailand",
};

export const navItems = [
  { href: "/", label: "Home" },
  {
    href: "/airport-transfer",
    label: "Airport Transfer",
    group: "transfers",
  },
  { href: "/hotel-transfer", label: "Hotel Transfer", group: "transfers" },
  { href: "/pier-transfer", label: "Pier Transfer", group: "transfers" },
  { href: "/beach-transfer", label: "Beach Transfer", group: "transfers" },
  { href: "/city-transfer", label: "City Transfer", group: "transfers" },
  {
    href: "/attraction-transfer",
    label: "Attraction Transfer",
    group: "transfers",
  },
  {
    href: "/inter-province-transfer",
    label: "Inter Province",
    group: "transfers",
  },
  { href: "/fleet", label: "Fleet" },
  { href: "/price-list", label: "Price List" },
  { href: "/tours", label: "Tours", group: "travel" },
  { href: "/boat-schedules", label: "Boat Schedules", group: "travel" },
  { href: "/travel-info", label: "Travel Info", group: "travel" },
  { href: "/articles", label: "Articles" },
  { href: "/faq", label: "FAQ" },
  { href: "/reviews", label: "Reviews" },
  { href: "/contact", label: "Contact" },
];

export const transferPages = {
  "airport-transfer": {
    title: "Airport Transfer",
    subtitle: "Reliable transfers to and from Krabi & Southern Thailand airports",
    category: "airport" as const,
    locationTypes: ["airport"] as const,
    featuredRoutes: [
      ["kbv-airport", "ao-nang-beach"],
      ["kbv-airport", "centara-ao-nang"],
      ["kbv-airport", "krabi-town"],
      ["kbv-airport", "railay-beach"],
      ["phuket-airport", "patong-beach"],
      ["kbv-airport", "phuket-airport"],
    ] as const,
    vehicleCodes: ["ECO", "PREM", "SUV", "VAN"] as const,
  },
  "hotel-transfer": {
    title: "Hotel Transfer",
    subtitle: "Door-to-door service to resorts and hotels across the region",
    category: "hotel" as const,
    locationTypes: ["hotel"] as const,
    featuredRoutes: [
      ["kbv-airport", "centara-ao-nang"],
      ["kbv-airport", "rayavadee"],
      ["krabi-town", "centara-ao-nang"],
      ["ao-nang-beach", "centara-ao-nang"],
      ["centara-ao-nang", "ao-nang-pier"],
      ["rayavadee", "railay-beach"],
    ] as const,
    vehicleCodes: ["ECO", "PREM", "SIG", "VIP"] as const,
  },
  "pier-transfer": {
    title: "Pier Transfer",
    subtitle: "Seamless connections to ferry piers and island departures",
    category: "pier" as const,
    locationTypes: ["pier"] as const,
    featuredRoutes: [
      ["kbv-airport", "ao-nang-pier"],
      ["krabi-town", "ao-nang-pier"],
      ["ao-nang-pier", "railay-beach"],
      ["ao-nang-pier", "phi-phi-pier"],
      ["centara-ao-nang", "ao-nang-pier"],
      ["kbv-airport", "phi-phi-pier"],
    ] as const,
    vehicleCodes: ["ECO", "SUV", "VAN", "VIP"] as const,
  },
  "beach-transfer": {
    title: "Beach Transfer",
    subtitle: "Direct transfers to Krabi's stunning beaches and coastal areas",
    category: "beach" as const,
    locationTypes: ["beach"] as const,
    featuredRoutes: [
      ["kbv-airport", "ao-nang-beach"],
      ["kbv-airport", "railay-beach"],
      ["krabi-town", "ao-nang-beach"],
      ["ao-nang-beach", "railay-beach"],
      ["phuket-airport", "patong-beach"],
      ["ao-nang-pier", "railay-beach"],
    ] as const,
    vehicleCodes: ["ECO", "PREM", "SUV", "VAN"] as const,
  },
  "city-transfer": {
    title: "City Transfer",
    subtitle: "Comfortable city-to-city transportation across Southern Thailand",
    category: "city" as const,
    locationTypes: ["city"] as const,
    featuredRoutes: [
      ["kbv-airport", "krabi-town"],
      ["krabi-town", "trang-town"],
      ["krabi-town", "surat-thani"],
      ["kbv-airport", "trang-town"],
      ["phuket-airport", "surat-thani"],
      ["krabi-town", "ao-nang-beach"],
    ] as const,
    vehicleCodes: ["ECO", "PREM", "SUV", "VAN"] as const,
  },
  "attraction-transfer": {
    title: "Attraction Transfer",
    subtitle: "Visit temples, national parks, and top tourist attractions",
    category: "attraction" as const,
    locationTypes: ["attraction", "temple", "park", "viewpoint"] as const,
    featuredRoutes: [
      ["krabi-town", "emerald-pool"],
      ["krabi-town", "tiger-cave"],
      ["krabi-town", "hot-spring"],
      ["kbv-airport", "tiger-cave"],
      ["emerald-pool", "hot-spring"],
      ["ao-nang-beach", "emerald-pool"],
    ] as const,
    vehicleCodes: ["ECO", "SUV", "VAN", "VIP"] as const,
  },
  "inter-province-transfer": {
    title: "Inter Province Transfer",
    subtitle: "Long-distance transfers between provinces in Southern Thailand",
    category: "inter-province" as const,
    locationTypes: ["province", "city", "airport"] as const,
    featuredRoutes: [
      ["kbv-airport", "phuket-airport"],
      ["krabi-town", "trang-town"],
      ["krabi-town", "surat-thani"],
      ["kbv-airport", "trang-town"],
      ["phuket-airport", "surat-thani"],
      ["kbv-airport", "surat-thani"],
    ] as const,
    vehicleCodes: ["SUV", "VAN", "VIP", "BUS"] as const,
  },
};

export type TransferPageKey = keyof typeof transferPages;
